//Saga Constant
export const LOGIN_SAGA = "LOGIN_SAGA";
export const GET_ALL_PROJECT_SAGA = "GET_ALL_PROJECT_SAGA";
export const GET_ALL_USER_SAGA = "GET_ALL_USER_SAGA";
export const ASSIGN_USER_PROJECT_SAGA = "ASSIGN_USER_PROJECT_SAGA";
export const DELETE_PROJECT_SAGA = "DELETE_PROJECT_SAGA";
export const GET_CATEGORY_SAGA = "GET_CATEGORY_SAGA";
export const CREATE_PROJECT_SAGA = "CREATE_PROJECT_SAGA";
//Reducer Constant
export const GET_ALL_PROJECT = "GET_ALL_PROJECT";
export const HIDE_LOADING = "HIDE_LOADING";
export const DISPLAY_LOADING = "DISPLAY_LOADING";
export const GET_ALL_USER = "GET_ALL_USER";
export const MODAL_CREATE = "MODAL_CREATE";
export const MODAL_EDIT = "MODAL_EDIT";
export const GET_CATEGROY = "GET_CATEGORY";
export const FUNCTION_SUBMIT = "FUNCTION_SUBMIT";
